// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    'Button': string;
    'colored': string;
    'simple': string;
}
export const cssExports: CssExports;
export default cssExports;
