name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    name: Linting, testing, building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: unit
