name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Installing modules and building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: building storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: storybook:build
  lint:
    name: Linting
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
  testing:
    name: Testing
    needs: [ build, lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: unit
