name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: build production project
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: unit testing
        uses: borales/actions-yarn@v4
        with:
          cmd: unit
